### ISSUE TITLE
JWT in krakend

### ISSUE THREAD

**Issue by vm-affekt** [devopsfaith/krakend.io#1]
Hello. I use KrakenD as a Golang library. I want to include JWT signing/validation in my gateway. Here is my endpoint config for signer:  
```json
{
        "endpoint": "/token",
        "method": "POST",
        "backend": [
          {
            "host": [
              "http://127.0.0.1:8090"
            ],
            "method": "GET",
            "url_pattern": "/token"
          }
        ],
        "extra_config": {
          "github.com/devopsfaith/krakend-jose/signer": {
            "alg": "HS256",
            "kid": "sim2",
            "keys-to-sign": ["access_token", "refresh_token"],
            "jwk-url": "http://localhost:8090/jwk",
            "disable_jwk_security": true
          }
        }
     }
```
And I define my RouterFactory via config below:
```golang
	routerFactory := krakendgin.NewFactory(krakendgin.Config{
		Engine:         gin.Default(),
		Middlewares:    []gin.HandlerFunc{},
		HandlerFactory: jose.HandlerFactory(krakendgin.EndpointHandler, logger, nil), 
		ProxyFactory:   proxyFactory,
		Logger:         logger,
		RunServer:      router.RunServer,
	})
```
When I start my application, KrakenD prints errors to log for each endpoint: 
```
[KRAKEND] ERROR: JOSE: no signer config /healthcheck
[KRAKEND] ERROR: JOSE: no signer config /billing/client/:id
[KRAKEND] ERROR: JOSE: no signer config /billing/client/
```
I understand that it's not good. What is correct way to include component to KrakenD?
Thanks.

**Comment by kpacha** [comment]
hi, @vm-affekt 

this repo is for the krakend.io website, not for the [KrakenD framework](https://github.com/devopsfaith/krakend) or the [JOSE](https://github.com/devopsfaith/krakend-jose) component.

Anyway, the logs are letting you know those endpoints will not "sign" responses and the system should work as expected.

Best
